name: Docs to PDF/HTML

on:
  push:
    branches:
      - master

jobs:
  converttopdf:
    name: Build PDF/HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python url_changer.py
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: Markdown
          output_dir: docs
          build_html: true
      - name: update file and push to remote
        run: |
          git config --global user.name "Conversion bot"
          git config --global user.email "conversion@bot.com"

          git add -A
          git commit -m "Converting to pdf and html"
          git push
